const stores = [
  {
    name: 'Shoprite',
    bkimage: 'images/background/shoprite-bk.jpeg',
    hero: 'images/hero/bk1.jpg',
    logo: 'images/logo/shoprite-logo.jpeg',
    products: [
      {
        name: 'rice',
        price: 5000,
        image: 'images/product/product1.jpg',
        category: 'foodcupboard',
        id: 1,
        quantity: 1,
      },
      {
        name: 'milo',
        price: 2500,
        image: 'images/product/product2.jpg',
        category: 'breakfast',
        id: 2,
        quantity: 1,
      },
      {
        name: 'Golden morn',
        price: 1500,
        image: 'images/product/product3.jpg',
        category: 'lunch',
        id: 3,
        quantity: 1,
      },
      {
        name: 'Kings vegetable oil',
        price: 2700,
        image: 'images/product/product4.jpg',
        category: 'dinner',
        id: 4,
        quantity: 1,
      },
      {
        name: 'Nivea body cream',
        price: 1900,
        image: 'images/product/product5.jpg',
        category: 'supper',
        id: 5,
        quantity: 1,
      },
      {
        name: 'Ayoola Poundo Yam',
        price: 1600,
        image: 'images/product/product6.jpg',
        category: 'soup',
        id: 6,
        quantity: 1,
      }
    ],
  },
  {
    name: 'Spar',
    bkimage: 'images/background/spar-bk.jpeg',
    hero: 'images/hero/bk2.jpg',
    logo: 'images/logo/Spar.webp',
    products: [
      {
        name: 'rice',
        price: 5000,
        image: 'images/product/product1.jpg',
        category: 'foodcupboard',
        id: 7,
        quantity: 1,
      },
      {
        name: 'milo',
        price: 2500,
        image: 'images/product/product2.jpg',
        category: 'breakfast',
        id: 8,
        quantity: 1,
      },
      {
        name: 'Golden morn',
        price: 1500,
        image: 'images/product/product3.jpg',
        category: 'lunch',
        id: 9,
        quantity: 1,
      },
      {
        name: 'Kings vegetable oil',
        price: 2700,
        image: 'images/product/product4.jpg',
        category: 'dinner',
        id: 10,
        quantity: 1,
      },
      {
        name: 'Nivea body cream',
        price: 1900,
        image: 'images/product/product5.jpg',
        category: 'supper',
        id: 11,
        quantity: 1,
      },
      {
        name: 'Ayoola Poundo Yam',
        price: 1600,
        image: 'images/product/product6.jpg',
        category: 'soup',
        id: 12,
        quantity: 1,
      }
    ],
  },
  {
    name: 'Bokku',
    bkimage: 'images/background/bokku-bk2.jpeg',
    hero: 'images/hero/bk3.jpg',
    logo: 'images/logo/bokku-logo.png',
    products: [
      {
        name: 'rice',
        price: 5000,
        image: 'images/product/product1.jpg',
        category: 'foodcupboard',
        id: 13,
        quantity: 1,
      },
      {
        name: 'milo',
        price: 2500,
        image: 'images/product/product2.jpg',
        category: 'breakfast',
        id: 14,
        quantity: 1,
      },
      {
        name: 'Golden morn',
        price: 1500,
        image: 'images/product/product3.jpg',
        category: 'lunch',
        id: 15,
        quantity: 1,
      },
      {
        name: 'Kings vegetable oil',
        price: 2700,
        image: 'images/product/product4.jpg',
        category: 'dinner',
        id: 16,
        quantity: 1,
      },
      {
        name: 'Nivea body cream',
        price: 1900,
        image: 'images/product/product5.jpg',
        category: 'supper',
        id: 17,
        quantity: 1,
      },
      {
        name: 'Ayoola Poundo Yam',
        price: 1600,
        image: 'images/product/product6.jpg',
        category: 'soup',
        id: 18,
        quantity: 1,
      }
    ],
  }
];